instance_provision: 'on_demand'
gce_datacenter: 'us-east1'
gce_network: 'qa-vpc'
gce_image_username: 'scylla-test'

gce_image_minikube: 'https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts'
gce_instance_type_minikube: 'n1-highmem-8'
gce_root_disk_type_minikube: 'pd-ssd'
gce_root_disk_size_minikube: 120
minikube_version: '1.11.0'

n_db_nodes: 3

# '4.3.0' version doesn't work with GKE: https://github.com/scylladb/scylla/issues/8032
scylla_version: '4.2.0'
scylla_mgmt_agent_version: '2.2.1'
mgmt_docker_image: 'scylladb/scylla-manager:2.2.1'

# NOTE: If 'k8s_scylla_operator_docker_image' not set then the one from helm chart will be used.
# To test nightly builds define it like this: 'scylladb/scylla-operator:nightly'
k8s_scylla_operator_docker_image: ''
k8s_scylla_operator_helm_repo: 'https://storage.googleapis.com/scylla-operator-charts/latest'
k8s_scylla_operator_chart_version: 'latest'
k8s_cert_manager_version: '1.2.0'
k8s_deploy_monitoring: true

k8s_scylla_datacenter: 'gce'
k8s_scylla_rack: 'minikube'
k8s_scylla_cluster_name: 'sct-cluster'
k8s_scylla_disk_gi: 5
k8s_scylla_disk_class: ''


gce_image: 'https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7'
gce_instance_type_loader: 'e2-standard-2'
gce_root_disk_type_loader: 'pd-standard'
gce_n_local_ssd_disk_loader: 0

n_loaders: 1

gce_instance_type_monitor: 'e2-medium'
gce_root_disk_type_monitor: 'pd-standard'
gce_root_disk_size_monitor: 50
gce_n_local_ssd_disk_monitor: 0

n_monitor_nodes: 1

user_credentials_path: '~/.ssh/scylla-test'
use_preinstalled_scylla: true
backtrace_decoding: false

append_scylla_args: ''
docker_image: ''
backup_bucket_location: 'minio-bucket'
