# Test
test_duration: 3600
prepare_write_cmd: ["cassandra-stress write no-warmup cl=QUORUM n=4000000 -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=20 -pop seq=1..4000000 -log interval=30"]
stress_cmd: ["cassandra-stress mixed cl=QUORUM duration=48h -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=10 -pop seq=1..4000000 -log interval=90"]
run_fullscan: 'random, 30'
pre_create_schema: true

keyspace_num: 1000
batch_size: 100

space_node_threshold: 10485760

nemesis_class_name: 'ChaosMonkey'
nemesis_interval: 30

# Env
n_db_nodes: 6
n_loaders: 10
n_monitor_nodes: 1

instance_type_db: 'i3.8xlarge'
instance_type_loader: 'c5.4xlarge'
aws_root_disk_size_monitor: 100

user_prefix: 'longevity-1000-keyspaces'

# loader AMI with c-s ver. 4 and few fixes:
#  - fix NoSuchElementException
#  - enable control over both consistency levels: regular and serial
#  - bring shard awareness
regions_data:
  us-east-1:
    ami_id_loader: 'ami-0b94f0e897d884b1b'
  eu-west-1:
    ami_id_loader: 'ami-0bf19545bc7bc9e1f'
  us-west-2:
    ami_id_loader: 'ami-063a97bde47353690'
  eu-north-1:
    ami_id_loader: 'ami-04af71cc28c321f61'


# disables coredump on bad alloc temporary cause of https://github.com/scylladb/scylla/issues/4951
append_scylla_args: '--blocked-reactor-notify-ms 500'

# Manager
use_mgmt: true

# TODO: remove when https://github.com/scylladb/scylla-tools-java/issues/175 resolved
stop_test_on_stress_failure: false
