apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  namespace: default
spec:
  containers:
  - name: ${POD_NAME}
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - /bin/sh
      - -c
      - while true; do sleep 900 ; done
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
  restartPolicy: Always
