---
nameOverride: ""
fullnameOverride: ${SCT_K8S_SCYLLA_CLUSTER_NAME}

scyllaImage:
  repository: scylladb/scylla
  tag: ${SCT_SCYLLA_VERSION}
agentImage:
  repository: scylladb/scylla-manager-agent
  tag: ${SCT_SCYLLA_MGMT_AGENT_VERSION}

serviceAccount:
  create: true
  annotations: {}
  name: ${SCT_K8S_SCYLLA_CLUSTER_NAME}-member

alternator:
  enabled: false
  port: 8000
  writeIsolation: "always"

developerMode: false
cpuset: true
hostNetworking: true
automaticOrphanedNodeCleanup: true
sysctls: ["fs.aio-max-nr=2097152"]
backups: []
repairs: []
serviceMonitor:
  create: ${SCT_K8S_DEPLOY_MONITORING}

datacenter: ${SCT_K8S_SCYLLA_DATACENTER}
racks:
  - name: ${SCT_K8S_SCYLLA_RACK}
    scyllaConfig: "scylla-config"
    scyllaAgentConfig: "scylla-agent-config"
    members: 0
    storage:
      storageClassName: local-raid-disks
      capacity: ${SCT_K8S_SCYLLA_DISK_GI}Gi
    resources:
      limits:
        cpu: ${SCT_K8S_SCYLLA_CPU_N}
        memory: ${SCT_K8S_SCYLLA_MEM_GI}Gi
      requests:
        cpu: ${SCT_K8S_SCYLLA_CPU_N}
        memory: ${SCT_K8S_SCYLLA_MEM_GI}Gi
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                    - ${SCT_K8S_SCYLLA_DATACENTER}
      tolerations:
        - key: role
          operator: Equal
          value: scylla-clusters
          effect: NoSchedule
